### ISSUE TITLE
@actor Decorator Side Effects on Import

### ISSUE THREAD

**Issue by bryanapperson** [Bogdanp/dramatiq#102]
# Issues

The @actor decorator produces import side effects (connecting to the broker) when decorating a function defined at the module level.

## Checklist

* [ * ] Does your title concisely summarize the problem?
* [ * ] Did you include a minimal, reproducible example?
* [ * ] What OS are you using?
* [ * ] What version of Dramatiq are you using?
* [ * ] What did you do?
* [ * ] What did you expect would happen?
* [ * ] What happened?

## What OS are you using?

Reproducible across Mac and Linux.

## What version of Dramatiq are you using?

1.3.0

## What did you do?

Define a module with a decorated function and import it.

some_module.py
```python
import dramatiq
import from app.broker import get_broker

@dramatiq.actor(broker=get_broker())
def some_thing():
    pass
```

```python
import some_module

def do_something():
    some_module.some_thing.send()
```

## What did you expect would happen?

The module would import without side effects and the broker would be lazy loaded when the Actor.send method was called. Maybe by adding the ability to pass a broker factory to the actor decorator.

## What happened?

The decorator produced an import side effect of needing to establish the connection to the broker immediately on module import. Importing a module should not have side effects, so I had to nest the function that needed the broker inside another wrapper function so that the module could be imported without automatically opening a connection.

## Ideas

Maybe something like this could eliminate the side effect:

some_module.py
```python
import dramatiq
import from app.broker import get_broker

@dramatiq.actor(broker_factory=get_broker)
def some_thing():
    pass
```

```python
import some_module

def do_something():
    some_module.some_thing.send()
```

Where if the broker factory is defined then the  broker would not be created until the send method.

**Comment by Bogdanp** [comment]
This is intentional and a core part of the design that's not likely to change in 1.x.  This simplifies the implementation of `send()` as queues are guaranteed to be created by the time the actor is called (though it's arguably less reliable than optimistically sending messages and creating the queue then retrying on failure if you happen to delete the queue after your workers boot up -- which is why I may make this change in 2.0 (I'm still undecided at this time), but I have no ETA on when that version might come out), and it ensures that things blow up at application boot time if something is misconfigured.

**Comment by bryanapperson** [comment]
Thanks for the fast response. I will just wrap the functions for now. For test cases I do use the stub broker. Thanks for the awesome project.
