### ISSUE TITLE
Subqueues

### ISSUE THREAD

**Issue by alanhamlett** [Bogdanp/dramatiq#109]
Feature Request: subqueues

More history on this found in https://github.com/Bogdanp/dramatiq/issues/99#issuecomment-399731863

**Comment by Bogdanp** [comment]
Closing this as wontdo for now. Sorry!

**Comment by ryanhiebert** [comment]
@alanhamlett : I'm interested in this feature, enough that I'm considering possibly writing it, but I'm using RabbitMQ with no desire to switch to Redis for the broker, since I rely heavily on AMQP's acks to get things back in the queue right away on worker collapse. Do you have any ideas on how RabbitMQ could provide subqueues? I've been looking over the concepts, and I haven't found a way yet, and I'm hoping that I'm just missing a good idea.

**Comment by ryanhiebert** [comment]
I created another repo that I'm going to use to work on the design of this feature, likely as a new broker. Nothing to see there yet, but it's a place to coordinate effort for those that might be interested.

https://github.com/ryanhiebert/dramatiq-subqueues
