### ISSUE TITLE
Add a mention of tasks persistence in the doc

### ISSUE THREAD

**Issue by sametmax** [Bogdanp/dramatiq#14]
I couldn't find in the doc if tasks were persisted or lost on the queue restart. If they are, what method is used ? What are the guaranties ?

**Comment by Bogdanp** [comment]
Dramatiq has at-least-once semantics. Both RabbitMQ and Redis persist their messages to disk (how often depends on your fsync settings for either of them) so if you restart the broker your messages will survive and will be delivered. If you kill your workers while they're processing messages then any messages in flight will be redelivered later (messages are only acknowledged to the broker once they've finished processing).

I'll write this down in a doc later this week. Thanks!

**Comment by Bogdanp** [comment]
@sametmax I'm curious, where have you looked for this information/where would you have liked to have seen it? As the docs grow bigger, I'm trying to figure out how to lay things out so they're discoverable (as a counterexample, Celery has a ton of docs that nobody can navigate so that's something I'm trying to avoid).

**Comment by sametmax** [comment]
I CTRL + Fed the doc table of content  for "persistence", "transient" and "stor". I tried it in the search engine to. Then I google "site:doc the same thing". Then not seing anything about it, I went to the sections talking about Redis and Rabbit hoping to find something about it. Especially, I was wondering if I could find a section about where the results / exceptions of the tasks where saved for later retrieval.
