### ISSUE TITLE
Queue task directly based on actor name

### ISSUE THREAD

**Issue by Ashish-Bansal** [Bogdanp/dramatiq#212]
Hi @Bogdanp,

https://discuss.dramatiq.io seems to be down. So, I'm posting here instead.

First of all, thanks a lot for this project. Those bugs in celery really sucks. I went through the code and it's insanely straight forward. 

I was looking for [send_task](https://docs.celeryproject.org/en/latest/reference/celery.html#celery.Celery.send_task) in the API docs and couldn't find anything. I think it's good feature to have. Let me know what do you think about it. I can open a PR for the same.

**Comment by Bogdanp** [comment]
I can't view the celery docs because their SSL cert expired, but you can instantiate [Message](https://dramatiq.io/reference.html#dramatiq.Message)s directly and then [enqueue](https://dramatiq.io/reference.html#dramatiq.Broker.enqueue) them on a broker.  Does that help?

Also, thank you for the kind words and the new discussion board is at https://www.reddit.com/r/dramatiq/ .

**Comment by Ashish-Bansal** [comment]
Oh okay. Thanks!
