### ISSUE TITLE
Retries middleware options are ignored if task receives SIGKILL or equivalent while running

### ISSUE THREAD

**Issue by MihaiBalint** [Bogdanp/dramatiq#213]
# Issues

Steps to reproduce:
1. Create a task that does something insignificant (for .e.g sleeps for 5 mins)
2. Configure the task with max_retry=3 times. Start the worker and the task.
3. Find the task pid and send SIGKILL to it. Notice that the task is restarted immediately
4. Repeat this 5 or more times and notice that the task is restarted immediately every time even after the the number of retries exceeds the configured max_retry.

In production the process could be killed because the task ran out of memory and the kernel OOM selected to kill it.

This could also be automated by having a task that simply performs suicide using something like this: os.kill(os.getpid(), signal.SIGKILL).

I would expect the max_retry and other options from the Retires middleware to also work if the task process is terminated abruptly.

## What OS are you using?

Using Linux, Ubuntu 18.04.

## What version of Dramatiq are you using?

dramatiq 1.6.0

**Comment by Bogdanp** [comment]
This is to be expected and the behavior you're seeing has nothing to do with the Retries middleware.

Dramatiq has at-least-once message processing semantics.  When a message is received from the broker, it is put in a special lease state on the broker and only after the message is successfully processed by a worker is it removed from the broker.  If the Dramatiq worker that is processing said message is killed before it can remove the message (i.e. "acknowledge" that is has been processed), then the broker will expire the lease and put the message back into circulation for another worker to process it at a later time.

If we were to implement some sort of eager-acknowledgement functionality (we won't, because that's basically never what you want), the result would be even worse.  The message would be received from the broker and immediately acknowledged, the worker would then be killed *while* processing the message. Since the worker has been killed, there's no one to run the `Retries` middleware and the message has been deleted from the broker (due to us acknowledging it early).  Poof goes the message!

As far as I'm aware, there is no way to tell RMQ that a message can only be leased a certain number of times and, while adding this to the Redis broker would be possible, I think it would introduce a lot of unnecessary complexity.  The solution to your problem (assuming it's the OOM-killing you mentioned) is to track down whatever is causing the memory leaks or to provision larger machines to run your workers.

**Comment by george-miller** [comment]
@Bogdanp 
I am running into this as well, dramatiq infinitely reruns a message when the message causes the worker to get OOMKilled.  After reading a bunch of code, it looks to me like instead of using `after_process_message` in retries.py you could just use `before_process_message` to record the same information.  Instead of recording `retries` just record `tries` (or `attempts` if that's better semantically).  If you come upon a message that has already been tried x times, just call `message.fail()` and it should be the same behavior right?  

I'm not opposed to taking a stab at it and submitting a PR.  The only wrench would be the exponential backoff, but I think I could make it happen.  

I do agree the best solution is to just not have memory leaks or OOMKills or unexpected memory increases, but honestly I feel like this would help make dramatiq an even more resilient task runner.

**Comment by george-miller** [comment]
Please see my first attempt here! https://github.com/Bogdanp/dramatiq/pull/383

**Comment by damianmoore** [comment]
It's really frustrating that Dramatiq doesn't handle this. Ideally, yes you shouldn't let tasks run out of memory but it does happen.

My use case is:
- People upload audio files of varying lengths and sizes.
- Large Kubernetes pods are launched just for processing (charged by the second and tweaked in terms of RAM/CPU).
- I want to process the audio as quickly as possible as the user is often waiting and I want to use as much of the expensive machine resources as possible.
- My code chunks up the big tasks into 5 minute sections of audio and creates a bunch of smaller tasks.
- My code in the worker pods starts workers dynamically based on number and types of items in queues and remaining pod memory (to save memory and try to prevent OOMs).
- If any workers get killed it's not a big problem but the work must be completed.

I've migrated everything from django-db-queue to RQ and now to Dramatiq. The features "Automatic retries" and "Reliable delivery" in the "[Motivation](https://dramatiq.io/motivation.html)" section of the docs made me think Dramatiq must be able to do this.

I'd be thankful to hear any suggestions of how to proceed. It seems like Celery can do this using `acks_late=True` and `task_reject_on_worker_lost` options ([Source](https://github.com/celery/celery/issues/5106)). I'll probably try and hack Dramatiq for a bit longer and then try Celery or a custom solution.
