### ISSUE TITLE
Global dead_message_ttl and no routing-key

### ISSUE THREAD

**Issue by evstratbg** [Bogdanp/dramatiq#255]
1.  Any reasons why dead_message_ttl is global?
Some dead letters should be returned faster, than default value (which is huge)

2. Any reasons why queue_name is used instead of routing-key at RMQ?
It isn't the same. It's ok, when Direct Exchange is set. In other cases, it will break all RabbitMQ advantages.

Gonna implement that, if the current solution was written for no reason

**Comment by Bogdanp** [comment]
Re. 1: it's global because you're not supposed to have too many dead messages. The TTL is large so you get a chance to inspect them and figure out what went wrong.

Re. 2: Messages *are* sent via the routing keys of their associated queues so I'm not sure exactly what you mean. Dramatiq uses the default (direct) exchange so this is entirely appropriate. If you need to use fanout exchanges or something else, then you can create a separate exchange. Dramatiq isn't intended for broadcasting use-cases, although I'm sure you could hack something together using a custom broker.
