### ISSUE TITLE
Feature Request: RQ like dashboard

### ISSUE THREAD

**Issue by benjaminweb** [Bogdanp/dramatiq#26]
How big would the effort be to implement a no bells and whistles dashboard like RQ?

http://python-rq.org/docs/monitoring/

**Comment by Bogdanp** [comment]
This is on my roadmap! :)

Since RabbitMQ is the primary broker for Dramatiq, this is going to be a little more difficult to implement than it was for RQ. That said, I think I have a good path forward, I just need to find the time to do it.

**Comment by benjaminweb** [comment]
Brilliant =).

**Comment by pirate** [comment]
If you're using dramatiq with django, there's a nice dashboard to view tasks automatically in the django admin.  It would be cool to have a standalone `pip install dramatiq-dashboard` project that provides separately though.

**Comment by Bogdanp** [comment]
Here's a little sneak preview of what I'm working on:

![Imgur](https://i.imgur.com/6WKgL4F.png)

No ETA yet as this is all pretty experimental and I only have about an hour or two a week to attend to it right now.

**Comment by benjaminweb** [comment]
Looks promising. How would ``add(some_dict)`` behave in the most intuitive way?

**Comment by Bogdanp** [comment]
@benjaminweb right now it shows the entire "repr" of the call. So that might look something like this:


```python
some_actor({"foo": 42})
```

That'd probably get unwieldy for very large dicts so I'll have to come up w/ a way to shorten them eventually. Maybe a simple regexp `re.sub("{...}", "{[^}]+}", representation)`. You'd still be able to see the full arguments by clicking on the message.

**Comment by benjaminweb** [comment]
Oh, that's quite sophisticated and detail oriented. I appreciate your attitude! Keep it up!

**Comment by jmagnusson** [comment]
Looks promising! Would there be a way to remove messages from the queue in this UI? I'd love to not have to fire up the redis-cli and do it manually.

**Comment by Bogdanp** [comment]
@jmagnusson yes, something like that will be possible. It won't remove the message from the broker, but the workers will be able to skip it when they do receive it.

**Comment by jmagnusson** [comment]
@Bogdanp Nice! Would there be any chance that you could add removal of messages as well?

**Comment by Bogdanp** [comment]
@jmagnusson removal isn't possible in RMQ as far as I'm aware and RabbitMQ is my main focus with Dramatiq so I probably won't be adding removal.

**Comment by jmagnusson** [comment]
Alright, fair enough. Would you be willing to accept PRs for Redis task deletion once it's been released?

**Comment by newfriend1** [comment]
@Bogdanp when this feature will be released?

**Comment by Bogdanp** [comment]
@jmagnusson I'm considering making it pluggable so you could potentially write your own package to extend its functionality without having to have that functionality in the core dashboard package.

@newfriend1 hard to say. I'm not currently actively working on this because I don't have the time right now.

**Comment by tyan4g** [comment]
need this ...

**Comment by lucawen** [comment]
any prevision for release dashboard or something go track/control the queue?

**Comment by menshikh-iv** [comment]
@Bogdanp sorry for annoying, any updates about this task? 
Can you share what you already did for this task, this will be really helpful for users!

**Comment by Bogdanp** [comment]
One of the reasons this was delayed by so much is because I wanted to support both RMQ and Redis in the same dashboard, but that would require too many changes to Dramatiq itself. With that in mind, I've decided that the dashboard will only support Redis for now.

If you're feeling adventurous, you can play around with it at https://github.com/bogdanp/dramatiq_dashboard .
