### ISSUE TITLE
Sponsoring options

### ISSUE THREAD

**Issue by timdrijvers** [Bogdanp/dramatiq#340]
We recently migrated our Celery stack to Dramatiq and are big fans of your software. I see that recently links to sponsoring platforms got removed from the README file. As an organisation we would like to sponsor you, will there be any new ways to support you in maintaining Dramatiq?

**Comment by Bogdanp** [comment]
Thanks for offering! I've dropped the sponsorship options because they felt like a burden for a number of reasons I won't try to summarize here. I think the best I can offer right now is to add a link to your company's website on the `README` and on the website for a monthly or yearly fee. That way you're guaranteed to get something in return for your money and I don't have to feel bad about not having the time/energy to spend on the project while taking your money. If that interests you, please feel free to shoot me an e-mail and we can talk about it.
