### ISSUE TITLE
Redis server crash when delayed messages are greater than the LUA stack

### ISSUE THREAD

**Issue by ethervoid** [Bogdanp/dramatiq#433]
# Issues

GitHub issues are for bugs.  If you have questions, please ask them on the [discussion board](https://reddit.com/r/dramatiq).

## Checklist

* [x] Does your title concisely summarize the problem?
* [ ] Did you include a minimal, reproducible example?
* [x] What OS are you using?
* [x] What version of Dramatiq are you using?
* [x] What did you do?
* [x] What did you expect would happen?
* [x] What happened?

## What OS are you using?

ECS Fargate (probably is Amazon linux)

## What version of Dramatiq are you using?
1.11.0

## What did you do?
We're running the last version of Dramatiq, when we suffered a huge peak of traffic and received information from our Redis provider that our cluster was crashing with this message: `lua stack limit reach when parsing redis.call reply`

So the problem is we reached the limit of the LUA stack for our Redis interpreter, which has an 8000 limit.

The command being executed was:

```
argv[0]: 'EVALSHA'
argv[1]: '56816d9e79234cb13c1451e28e4bde853b6cae2e'
argv[2]: '1'
argv[3]: 'dramatiq'
argv[4]: 'fetch'
argv[5]: '1642399652204'
argv[6]: 'dispatch_events_queue.DQ'
argv[7]: 'f025a5dc-8a51-4ce9-b07c-7759374571cd'
argv[8]: '60000'
argv[9]: '604800000'
argv[10]: '0'
argv[11]: '7992'
argv[12]: '8000'
```

## What did you expect would happen?

No server crash if the number of delayed messages are increasing

## What happened?

The server crashed, the AOF register write commands, and failed to restart again due to not be able to execute the command and crashing again due to the StackOverflow.

I've been checking the Redis code and basically, the server crashes when the command is not able to perform an increase in the LUA stack, like [this example](https://github.com/redis/redis/blob/b874c6f1fcf844d28f84fc2a2ab6b8f6c2458462/src/scripting.c#L172-L175) , but the weird thing is that every script, `EVALSHA` execution, is atomic so the crash could only happen in the script execution.

As you can see in the crashed command, we're getting 7992 messages and performing actions on them but then we need to convert types from Redis to LUA, and then we're growing more than 1 element in the stack, for example [here](https://github.com/redis/redis/blob/b874c6f1fcf844d28f84fc2a2ab6b8f6c2458462/src/scripting.c#L270-L274) we're trying to increase the current stack by 3

I have a possible fix which is to make it possible to tune the number of prefetched delay messages, like [here](https://github.com/Bogdanp/dramatiq/blob/7751c1d774522bd6dc1a773c9ab2c3b844245776/dramatiq/worker.py#L46) but I'm not able to reproduce the root cause and I think we need to know why is happening that before implementing a fix for it

**Comment by Bogdanp** [comment]
Thanks for the detailed report! I think we can do two things here. The first would be to adjust the broker so that it sets its max stack value (returned by [maxstack.lua](https://github.com/Bogdanp/dramatiq/blob/d5737fb77a2efc2ebfed216a24d932800d9635f9/dramatiq/brokers/redis/maxstack.lua)) to half the max. The second would be to make the max stack value configurable via an env var. So probably it could be as simple as making [this](https://github.com/Bogdanp/dramatiq/blob/d5737fb77a2efc2ebfed216a24d932800d9635f9/dramatiq/brokers/redis.py#L245) default to an env var or `None` and changing the code that sets the max stack val the first time to set it to half or 2/3 of what it gets from `maxstack.lua`.

Let me know if you want to make a PR for this, otherwise I can do it.

**Comment by ethervoid** [comment]
Thank you for answering. I agree with the solutions so I'll create a PR for it ☺️
