### ISSUE TITLE
question: how to avoid processing the same message multiple times

### ISSUE THREAD

**Issue by MattBlack85** [Bogdanp/dramatiq#53]
the contribution guidelines says to ask on SO, but mine is more a knowledge question and not a real problem. From docs I understand that messages are acked after they're processed. It's not clear to me tho how I can avoid to have a message grabbed by multiple workers (do I have to implement myself a distributed lock or something?). @Bogdanp do you have an IRC channel/gitter? If no it could be a nice place where people can ask this kind of questions maybe. Anyway good job, I'm very interested in your project and I'm planning to give it a go to see if we can replace the celery stuff we have now

**Comment by ericgj** [comment]
I think RabbitMQ gives you this guarantee with direct as opposed to fanout exchanges?  (And presumably the Redis broker does too although I'm not as familiar with it.)

**Comment by Bogdanp** [comment]
There is a Gitter [here](https://gitter.im/dramatiq/dramatiq) but I'm the only one on it.  I should add it to the README. :D

I could use a concrete example here because I'm having trouble understanding exactly what you're asking. One message will only be delivered to one worker, unless it fails and gets retried, but then even the retries will each make it to one worker at a time.

If you want a specific actor to only process one message at a time, then yes, you can use a distributed lock (check out the docs here: https://dramatiq.io/cookbook.html#rate-limiting).

**Comment by Bogdanp** [comment]
I'm closing this for now. @MattBlack85 feel free to re-open it if your question wasn't answered.
