### ISSUE TITLE
Python 2 Version

### ISSUE THREAD

**Issue by thomascrha** [Bogdanp/dramatiq#86]
I know this isn't going to be received well. I also despise python2 and its zombie like status. I've got a project which is python2 and I'm really hating using Celery for obvious reasons. I'm in the process of refactoring the code to python2 for my use. Would this be something you wanted in the upstream ? 

I'm happy to do the work - I need a better solution then Celery and this lib is my choice when programming in Python3.

**Comment by Bogdanp** [comment]
I'd certainly like to take a look at what you come up with if you do get it working on Python 2, but it's unlikely that I'll merge those changes back to the main branch because of the extra maintenance (and code quality) burden for a language that is near its EOL.

You're probably going to run into this issue porting the `TimeLimits` middleware because of https://bugs.python.org/issue32057, btw. I'd suggest switching from using signals to trigger the alarm to using a thread that wakes up every now and then.

If you want to discuss this further or if you need any help, let's take this to the [forum](https://discuss.dramatiq.io).
