### ISSUE TITLE
Add tasktiger to comparison table

### ISSUE THREAD

**Issue by alanhamlett** [Bogdanp/dramatiq#99]
Request to add [tasktiger](https://github.com/closeio/tasktiger) to the [Compared To Table](https://dramatiq.io/motivation.html#compared-to).

**Comment by Bogdanp** [comment]
Thanks! tasktiger looks pretty cool. That said, I wouldn't feel too comfortable comparing it to dramatiq  in the official docs without having used it before. Sorry!

Based on their README, here are the main differences I perceive between it and dramatiq:

* tasktiger forks per task, this makes for a huge difference in throughput (it's likely one or two orders of magnitude slower than dramatiq -- this may or may not matter depending on what kinds of tasks you run)
* tasktiger is redis-only
* tasktiger doesn't seem like it has any mechanism for extensibility (no analogue to dramatiq's middleware)
* tasktiger doesn't do its own worker pooling, you need supervisor to run multiple worker processes
* tasktiger lets you inspect and manage the state of tasks once they've been pushed, dramatiq doesn't let you do this out of the box
* tasktiger supports task batching, dramatiq doesn't
* tasktiger has an admin dashboard, dramatiq doesn't (yet!)

Again, you should take this with a grain of salt, because I've never used tasktiger before. :)

**Comment by alanhamlett** [comment]
And one more difference: support for sub-queues to prevent bottlenecks

**Comment by Bogdanp** [comment]
> I don't think forking hurts throughput much since the fork happens after imports and setup.

You would be surprised. Here's how tasktiger does on the `fib` benchmark in this repo:

`Took 165.93364191055298 seconds to process 10000 messages.`

Here's how dramatiq does on the same machine:

`Took 3.9948761463165283 seconds to process 10000 messages.`

**Comment by alanhamlett** [comment]
Wow, I am surprised! Also after looking more into dramatiq I'm impressed. The only thing it's missing is sub-queues to prevent users bottlenecking other users by generating many tasks and clogging a queue.

**Comment by Bogdanp** [comment]
> The only thing it's missing is sub-queues to prevent users bottlenecking other users by generating many tasks and clogging a queue.

That's an interesting feature, though (I think!) queueing theory would suggest that's not better than a single queue assuming processing time varies per task: https://www.youtube.com/watch?v=F5Ri_HhziI0

**Comment by alanhamlett** [comment]
Interesting video, but subqueues aren't about overall queue performance they are about task prioritization. For example, imagine in that shopping line video that customers started giving one item to each of their children and had their children wait in line for the parent. The parent with the most children will get through the queue the fastest. So what if one parent (ParentZ) somehow has thousands of children... then all the other parents' children will be waiting in the queue because the thousands of children are clogging all lines.

Instead of increasing the number of lines/workers processing the queue, which costs money, you use a prioritization algorithm to process children from ParentZ **unless** there are other parent's children in line, in which case you treat all of ParentZ's children as one child so the other parent's children have a chance to get through the line.
